### ISSUE TITLE
latexmk not finding figures

### ISSUE THREAD

**Issue by michK** [mgeier/homepage#2]
I'm having the problem that `latexmk` doesn't find the figures in my document, where running `pdflatex' has no problem.

In my document I'm specifying the figure path as `\graphicspath{{figs/}}`.

Does `latexmk` perhaps not support the `\graphicspath{}` command?

Thanks in advance

**Comment by mgeier** [comment]
It should work, `latexmk` is normally just calling `pdflatex` internally.
Probably in your settings you are using some other executable?
Or you are not using the `-pdf` option?

Can you make a minimal example with only one image and nothing else to check if the error still happens?
If you post the example here, I can try if it works for me.

BTW, I've read somewhere that using `\graphicspath{}` may cause your LaTeX run to be slower, especially if you use multiple paths (which you probably don't).
Since then, I stopped using `\graphicspath{}` and just add the subdirectory explicitly, like `\includegraphics{figs/myfig01}`. It isn't really a problem to type a few characters, and should you decide to move your graphics, it should be easy for your text editor to bulk-replace all occurrences, right?

**Comment by michK** [comment]
Thank you, you were right, it's because I didn't specify the `-pdf` option.

Thanks for the `\gpaphicspath{}` hint, I will be sure to remember that. Sometimes I do actually use various paths, so it's good to know that will make it slower.

Regards
